### ISSUE TITLE
Add support for 'init' command to initialize pkgcloud-cli.json file

### ISSUE THREAD

**Issue by Phanatic** [pkgcloud/pkgcloud-cli#17]
Running pkgcloud-cli init should initialize an empty pkgcloud-cli.json file in the user's home directory.

**Comment by rosskukulinski** [comment]
@meteormatt / @Phanatic - I'd be happy to accept a PR for this, should be simple.  Otherwise, I won't be opening my editor back up until after January 6th.

**Comment by rosskukulinski** [comment]
@meteormatt @Phanatic this was released on npm as pkgcloud-cli@1.1.1

**Comment by Phanatic** [comment]
@rosskukulinski, thanks! I was out on vacation and didn't see your earlier message.

**Comment by rosskukulinski** [comment]
Thanks for the idea!

**Comment by meteormatt** [comment]
@rosskukulinski :clap:
